# Test using cuTile's API to generate bytecode for comparison

using cuTile

# Simplest possible function to generate bytecode
function simple_func()
    return 42
end

# Generate Tile IR for this function using cuTile's API
try
    println("=== Generating Tile IR using cuTile API ===")
    ir = cuTile.code_tiled(simple_func, ())
    println("Generated IR:")
    println(ir)

    # Try to get the bytecode
    println("\n=== Getting bytecode ===")
    bytecode = cuTile.code_tiled_binary(simple_func, ())
    println("Bytecode length: $(length(bytecode)) bytes")
    println("First 64 bytes: ", bytes2hex(bytecode[1:min(64, length(bytecode))]))

    # Save to file and try to disassemble
    temp_file = tempname() * ".tile"
    write(temp_file, bytecode)

    try
        # Use cuTile's translate tool to disassemble
        println("\n=== Disassembling cuTile API generated bytecode ===")
        disasm_cmd = `$(cuTile.cuda_tile_translate()) --cudatilebc-to-mlir $temp_file`
        disasm = read(disasm_cmd, String)

        println("SUCCESS! Disassembled output:")
        println(disasm)
        return true
    catch e
        println("\nDisassembly of cuTile API bytecode failed: $e")
        return false
    finally
        rm(temp_file, force=true)
    end

catch e
    println("Failed to generate Tile IR using cuTile API: $e")
    return false
end

# Try to generate a minimal scan function
function simple_scan(arr::Vector{Int32})
    result = similar(arr)
    result[1] = arr[1]
    for i in 2:length(arr)
        result[i] = result[i-1] + arr[i]
    end
    return result
end

println("\n\n=== Trying with scan function ===")
try
    ir = cuTile.code_tiled(simple_scan, (Vector{Int32},))
    println("Generated scan IR:")
    println(ir)

    # Try to get the bytecode
    println("\n=== Getting scan bytecode ===")
    bytecode = cuTile.code_tiled_binary(simple_scan, (Vector{Int32},))
    println("Bytecode length: $(length(bytecode)) bytes")
    println("First 64 bytes: ", bytes2hex(bytecode[1:min(64, length(bytecode))]))

    # Save to file and try to disassemble
    temp_file = tempname() * ".tile"
    write(temp_file, bytecode)

    try
        # Use cuTile's translate tool to disassemble
        println("\n=== Disassembling cuTile API scan bytecode ===")
        disasm_cmd = `$(cuTile.cuda_tile_translate()) --cudatilebc-to-mlir $temp_file`
        disasm = read(disasm_cmd, String)

        println("SUCCESS! Disassembled output:")
        println(disasm)
        return true
    catch e
        println("\nDisassembly of cuTile API scan bytecode failed: $e")
        return false
    finally
        rm(temp_file, force=true)
    end

catch e
    println("Failed to generate scan IR using cuTile API: $e")
    return false
end
